# Generated by Django 5.0.6 on 2024-07-02 14:14

import myFirstapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to=myFirstapp.models.image_file_dir)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
