# Generated by Django 5.0.6 on 2024-08-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstapp', '0002_alter_blog_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page_Vist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
