# Generated by Django 5.0.6 on 2024-08-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstapp', '0003_page_vist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page_vist',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
